# Install ruby by way of rbenv.
---
- name: ruby
  hosts: all
  vars_files:
  - vars.yml
  remote_user: root
  tasks:

  - name: install apt prerequisites
    apt: pkg={{ item }} state=installed
    with_items:
    - build-essential
    - libssl-dev
    - libreadline-dev
    - libyaml-dev
    - libsqlite3-dev
    - sqlite3
    - libxml2-dev
    - libxslt1-dev
    - zlib1g-dev

- hosts: all
  vars_files:
  - vars.yml
  remote_user: "{{ username }}"
  tasks:

  - name: install rbenv
    git: repo=https://github.com/sstephenson/rbenv.git
         dest={{ rbenv_root }}

  - name: install ruby-build
    git: repo=https://github.com/sstephenson/ruby-build.git
         dest={{ rbenv_root }}/plugins/ruby-build

  - name: build ruby {{ ruby_version }}
    shell: chdir={{ home }} rbenv install {{ ruby_version }}
           creates={{ rbenv_root }}/versions/{{ ruby_version }}/bin/ruby
    environment: rbenv_env

  - name: set the global ruby version to {{ ruby_version }}
    command: chdir={{ home }}
             rbenv global {{ ruby_version }}
    environment: rbenv_env

  - name: rehash to pick up changes
    command: chdir={{ home }}
             rbenv rehash
    environment: rbenv_env
